---
name: Test-Ping
version: 0.07
author:
  - 'Sawyer X <xsawyerx@cpan.org>'
abstract: Testing pings using Net::Ping
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Net::Ping: 2.33
  Test::Builder: 0.86
  Tie::Scalar: 0
build_requires:
  Test::More: 0
provides:
  Test::Ping:
    file: lib/Test/Ping.pm
    version: 0.07
  Test::Ping::Ties::PORT:
    file: lib/Test/Ping/Ties/PORT.pm
    version: 0.01
  Test::Ping::Ties::PROTO:
    file: lib/Test/Ping/Ties/PROTO.pm
    version: 0.04
  Test::Ping::Ties::TIMEOUT:
    file: lib/Test/Ping/Ties/TIMEOUT.pm
    version: 0.02
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
